swagger: '2.0'
info:
  version: "0.0.1"
  title: AsyncFTP WEB UI

paths:
  /api/info:
    get:
      description: |
        Get `info` object which shows the current information of server.
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/info'
                
  /api/start:
    get:
      description: |
        Start the server.
      responses:
        200:
          description:  Successful response
        404:
          description: Something wrong :(
          
  /api/stop:
    get:
        description: |
          Stop the server.
        responses:
          200:
            description:  Successful response
          404:
            description: Something wrong :(
              
  /api/config:
    get:
      description: |
        Get the config of server.
      responses:
        200:
          description: Successful response
          schema:
            title: config
            type: object
            properties:
              host:
                type: string
              port:
                type: string
              version:
                type: string
              uptime:
                type: string
              refuse_ip:
                type: array
                items:
                  title: ip
                  type: string
    post:
      description: |
        Change the config of server.
      parameters:
        -
          name: config
          required: true
          in: body
          schema:
            $ref: '#/definitions/config'
      responses:
        200:
          description: Successful response
        
          
definitions:
  config:
    type: object
    properties:
      host:
        type: string
      port:
        type: string
      refuse_ip:
        type: array
        items:
          title: ip
          type: string
  info:
    type: object
    properties:
      speed:
        type: object
        properties:
          up:
            type: string
          down:
            type: string
      up_time:
        type: string